name = "preeknotities"
pages_build_output_dir = "/"  # Or your build output directory (e.g., "build", "public", "out")
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # This is the variable name you'll use in your code
database_name = "test"
database_id = "2a3ac4b9-ef51-41d8-9190-df50e2d0c79f" # From the create command output
